# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  # Every Friday at 20h
  - cron: '0 20 * * 5'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 365
        days-before-pr-stale: 30
        days-before-close: -1
        stale-issue-message: 'This issue has no activity for a long time, is it still relevant ?'
        stale-pr-message: 'This PR has no activity for a long time, is it still relevant ?'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
